apiVersion: content.hauler.cattle.io/v1
kind: Charts
metadata:
  name: cert-manager-chart
spec:
  charts:
    - name: cert-manager
      repoURL: https://charts.jetstack.io
      version: v1.19.0
---
apiVersion: content.hauler.cattle.io/v1
kind: Images
metadata:
  name: cert-manager-images
spec:
  images:
    - name: quay.io/jetstack/cert-manager-cainjector:v1.19.0
    - name: quay.io/jetstack/cert-manager-controller:v1.19.0
    - name: quay.io/jetstack/cert-manager-webhook:v1.19.0
    - name: quay.io/jetstack/cert-manager-startupapicheck:v1.19.0
